import { Inter } from 'next/font/google'
import '../globals.css'
import style from "../../../public/assets/styles/Login.module.css"
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 return (
   <>
      <div>
      <div className={style.wave}>
            <img src="/assets/images/wave.svg" alt="" />
        </div>
      </div>

     <main className={inter.className}>{children}</main>
   </>
 )
}